version: '2.3'

services:

  elasticsearch:
    image: elasticsearch:7.9.3
    restart: on-failure
    networks:
      - internal
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - transport.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=searcher
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9300'
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  mysql:
    image: mysql:5.7
    restart: on-failure
    networks:
      - internal
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      - MYSQL_ROOT_PASSWORD=Root@1234
      - MYSQL_DATABASE=searcher
      - MYSQL_USER=searcher
      - MYSQL_PASSWORD=searcher
      - MYSQL_INITDB_SKIP_TZINFO=NONE
    healthcheck:
      test: [ "CMD-SHELL", 'mysqladmin ping -u root -pRoot@1234' ]
      interval: 15s
      timeout: 10s
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  searcher:
    image: searcher:latest
    build:
      context: .
    depends_on:
      mysql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    links:
      - elasticsearch:elasticsearch
      - mysql:mysql
    networks:
      - internal
    ports:
      - 1987:1987
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=searcher
      - MYSQL_USERNAME=searcher
      - MYSQL_PASSWORD=searcher
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - SPRING_PROFILES_ACTIVE=mysql
    healthcheck:
      test: ["CMD", "curl","-I" ,"-XGET", "http://localhost:1987/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

networks:
  internal: